### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by kaigunkuzan** [kaigunkuzan/chat-space#16]
#IPアドレス
18.176.209.25

**Comment by kohei-isoda** [comment]
伊勢田さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**◯ サイドバーのユーザー名の後ろにmasaと付いてしまうので修正してください**
[![Screenshot from Gyazo](https://gyazo.com/98c2a230ae728e0b012d7ee49b692e20/raw)](https://gyazo.com/98c2a230ae728e0b012d7ee49b692e20)

**◯ サイドバーにあるユーザー名の色が見づらいので#ffffffに変更してください**

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

[![Screenshot from Gyazo](https://gyazo.com/98c2a230ae728e0b012d7ee49b692e20/raw)](https://gyazo.com/98c2a230ae728e0b012d7ee49b692e20)

**Comment by kaigunkuzan** [comment]
確認ありがとうございます。
修正しております。

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！修正お疲れさまでした！
